"""add-id-to-roles

Revision ID: 9071a6221c19
Revises: ae4bc03d8fc4
Create Date: 2023-12-03 00:18:00.043907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9071a6221c19'
down_revision: Union[str, None] = 'ae4bc03d8fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_roles', sa.Column('id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'users_roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_roles', type_='unique')
    op.drop_column('users_roles', 'id')
    # ### end Alembic commands ###
