"""add-roles

Revision ID: ae4bc03d8fc4
Revises: f6a5d773b957
Create Date: 2023-12-02 23:50:19.247166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae4bc03d8fc4'
down_revision: Union[str, None] = 'f6a5d773b957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_roles',
    sa.Column('name', sa.Enum('USER', 'MANAGER', 'SUPERVISOR', 'ANALYST', 'TESTER', 'EXECUTOR', 'ADMIN', name='roles'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users_roles_map',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.Enum('USER', 'MANAGER', 'SUPERVISOR', 'ANALYST', 'TESTER', 'EXECUTOR', 'ADMIN', name='roles'), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['users_roles.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_name')
    )
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.add_column('users_logins', sa.Column('login_at', sa.DateTime(), nullable=False))
    op.add_column('users_logins', sa.Column('ip_address', sa.String(length=50), nullable=False))
    op.add_column('users_logins', sa.Column('user_agent', sa.String(length=255), nullable=False))
    op.drop_column('users_logins', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_logins', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users_logins', 'user_agent')
    op.drop_column('users_logins', 'ip_address')
    op.drop_column('users_logins', 'login_at')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('users_roles_map')
    op.drop_table('users_roles')
    # ### end Alembic commands ###
